version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/postgres
    networks:
      - app_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: test_wallet_user
      POSTGRES_PASSWORD: hardpassword
      POSTGRES_DB: wallets
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_wallet_user -d wallets"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:
    driver: bridge